#String: Route to be initialized
selected_routes: '/opt/carma/routes/'

# List of String: Required plugins for the platform to be functional
selected_plugins:
  - RouteFollowing
  - InLaneCruisingPlugin
  - StopAndWaitPlugin
  - Pure Pursuit